### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by wesinator**

### CODE REVIEW

**Comment by LiamSwayne** [comment]
It seems like this repo is completely unmaintained :(

**Comment by StanFromIreland** [comment]
@cyrillos @hpax

**Review by cyrillos — APPROVED** [review]
Thanks!

**Comment by cyrillos** [comment]
Merged it manually, thanks a lot!

**Comment by StanFromIreland** [comment]
@cyrillos why manually?

**Comment by cyrillos** [comment]
For some reason automerge didn't pass well

**Comment by StanFromIreland** [comment]
Weird. Did you mange to see my other PR or my Emails?

**Pull request closed without merging**
